default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 5000

development:
  <<: *default
  database: shopify_ruby_example_development
  username: postgres
  password: a

test:
  <<: *default
  database: shopify_ruby_example_test
  username: postgres
  password: a

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
